summon ds:projectile "flashstep"
scoreboard players set @e[type=ds:projectile,name="flashstep",r=1,c=1] Deleter 3
execute rotated ~ 0 as @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] positioned ^^^-1 run spreadplayers ~ ~ 3 9 @s
execute as @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] at @s if block ~~-1~ air run tp @s ~~-1~
execute as @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] at @s if block ~~-0.7~ air run tp @s ~~-0.7~
execute as @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] at @s if block ~~-0.5~ air run tp @s ~~-0.5~
execute as @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] at @s if block ~~-0.2~ air run tp @s ~~-0.2~
execute as @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] at @s if block ~~-0.2~ air run tp @s ~~-0.2~
execute as @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] at @s if block ~~-0.1~ air run tp @s ~~-0.1~



execute as @s[tag=!simpledomain_protecting,tag=!invisible] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run playsound mob.enderdragon.flap @a[r=50] ~~~ 0.25 0.7
execute as @s[tag=!simpledomain_protecting,tag=!invisible] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run playsound mob.blaze.shoot @a[r=50] ~~~ 0.25 1.7
execute as @s[tag=!simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players set @s Frames 6
execute as @s[tag=!simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players set @s flashstep 8
execute as @s[tag=!simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players add @s Disabled 5
execute as @s[tag=!simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run particle ds:sonido1

execute as @s[tag=simpledomain_protecting,tag=!invisible] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run playsound mob.enderdragon.flap @a[r=50] ~~~ 0.25 0.7
execute as @s[tag=simpledomain_protecting,tag=!invisible] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run playsound mob.blaze.shoot @a[r=50] ~~~ 0.25 1.7
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players set @s Frames 6
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players set @s flashstep 8
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players add @s Disabled 5
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run particle ds:sonido1

execute as @s[tag=simpledomain_protecting,tag=!invisible] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run playsound mob.enderdragon.flap @a[r=50] ~~~ 0.25 0.7
execute as @s[tag=simpledomain_protecting,tag=!invisible] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run playsound mob.blaze.shoot @a[r=50] ~~~ 0.25 1.7
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players set @s Frames 6
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players set @s flashstep 8
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run scoreboard players add @s Disabled 5
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air at @s run particle ds:sonido1


execute as @s[tag=!simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air run tp @s @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1]
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air run tp @s @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1]
execute as @s[tag=simpledomain_protecting] at @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=18,c=1] unless entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] unless block ~~-0.5~ air unless block ~~-0.5~ water unless block ~~-0.5~ lava if block ~~~ air if block ~~1~ air run tp @s @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1]



execute at @s unless entity @e[type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=7.5,c=1] if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] at @e[r=7.5,family=flyhead,c=1] at @e[rm=0.15,r=7.5,family=flyhead,c=1] if entity @s[r=7.5] run effect @s invisibility 2 11 true
execute at @s unless entity @e[type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=7.5,c=1] if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] if block ~~-1~ leaves run effect @s invisibility 2 11 true
execute at @s unless entity @e[type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=7.5,c=1] if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] if block ~~-1~ leaves2 run effect @s invisibility 2 11 true
execute at @s unless entity @e[type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=7.5,c=1] if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] if block ~~-1~ azalea_leaves run effect @s invisibility 2 11 true
execute at @s unless entity @e[type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=7.5,c=1] if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] if block ~~-1~ azalea_leaves_flowered run effect @s invisibility 2 11 true
execute at @s unless entity @e[type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=7.5,c=1] if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] if block ~~-1~ mangrove_leaves run effect @s invisibility 2 11 true
execute at @s unless entity @e[type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=7.5,c=1] if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] if block ~~-1~ cherry_leaves run effect @s invisibility 2 11 true
execute at @s if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] run effect @s speed 0 50 true
execute at @s if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] run effect @s slowness 1 2 true
execute at @s if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] run particle ds:sonido1
execute at @s[tag=!invisible] if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] run particle ds:evade3
execute at @s if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] run tp @s ~~~ facing @e[tag=target,tag=!unselect,family=!flyhead,r=80,c=1]
execute at @s if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] unless entity @e[tag=target,tag=!unselect,family=!flyhead,r=80,c=1] run tp @s ~~~ facing @e[scores={combat=1..},type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=80,c=1]
execute at @s if entity @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=1,c=1] unless entity @e[tag=target,tag=!unselect,family=!flyhead,r=80,c=1] unless entity @e[scores={combat=1..},type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=80,c=1] run tp @s ~~~ facing @e[type=!ds:toji,type=!ds:toji_boss,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!bat,family=!flyhead,tag=!dying,r=80,c=1]

execute as @e[type=ds:projectile,name="flashstep",scores={Deleter=3},r=60,c=1] at @s run tp @s ~~-200~