execute unless entity @s[scores={hitdodge=0..}] run scoreboard players add @s hitdodge 0

execute unless entity @s[scores={strength=101..}] run scoreboard players set @s[scores={hitdodge=10..},family=!special_grade] Stun 105
scoreboard players operation @s[scores={hitdodge=10..,strength=1..100},family=!special_grade] Stun -= @s strength

scoreboard players random @s[scores={strength=0..10,hitdodge=..9},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] DashCD -208 -195 
scoreboard players random @s[scores={strength=11..20,hitdodge=..9},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] DashCD -207 -195 
scoreboard players random @s[scores={strength=21..30,hitdodge=..9},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] DashCD -206 -195 
scoreboard players random @s[scores={strength=31..40,hitdodge=..9},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] DashCD -205 -195  
scoreboard players random @s[scores={strength=41..,hitdodge=..9},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] DashCD -204 -195 

scoreboard players random @s[scores={agility=21..30,hitdodge=..9},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] DashCD -206 -195 
scoreboard players random @s[scores={agility=31..40,hitdodge=..9},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] DashCD -205 -195 
scoreboard players random @s[scores={agility=41..,hitdodge=..9},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] DashCD -204 -195 

scoreboard players set @s[scores={hitdodge=10..}] hitdodge 0

execute if entity @e[family=projectile,tag=DomainExpansion,r=55] run scoreboard players set @s[scores={DashCD=!0},family=!heavenlyrestriction,tag=!domainimmune,tag=!domainactive] DashCD 0
execute if entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] run scoreboard players set @s[scores={DashCD=!0},tag=!domainactive] DashCD 0
execute if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] run scoreboard players set @s[scores={DashCD=!0},tag=!domainimmune,tag=!domainactive] DashCD 0

execute as @s[scores={DashCD=-198..},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=!customDashCD] at @s if entity @e[r=5,rm=0.15,scores={atk=1..},hasitem={item=ds:executioners_sword,location=slot.weapon.mainhand}] run scoreboard players random @s DashCD -203 -199



#---------------


scoreboard players set @s[tag=cannot_dodge] hitdodge 0
scoreboard players set @s[tag=cannot_dodge] DashCD 0

execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=!domainactive] at @s unless entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=!domainactive] at @s unless entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=!domainactive] at @s unless entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] run function dashright
execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=heavenlyrestriction,tag=!domainactive] at @s unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=heavenlyrestriction,tag=!domainactive] at @s unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=heavenlyrestriction,tag=!domainactive] at @s unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] run function dashright

execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainactive] at @s run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainactive] at @s run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainactive] at @s run function dashright
execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!domainactive] at @s unless entity @s[tag=!hollowwickerbasket,tag=!domainamplification] if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!domainactive] at @s unless entity @s[tag=!hollowwickerbasket,tag=!domainamplification] if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!domainactive] at @s unless entity @s[tag=!hollowwickerbasket,tag=!domainamplification] if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] run function dashright
execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!domainactive] at @s unless entity @s[tag=!hollowwickerbasket,tag=!domainamplification] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!domainactive] at @s unless entity @s[tag=!hollowwickerbasket,tag=!domainamplification] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!domainactive] at @s unless entity @s[tag=!hollowwickerbasket,tag=!domainamplification] unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] run function dashright



#regular sorcerer
execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^^^-6 if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^8^^ if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^-8^^ if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] run function dashright
execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^^^-6 unless entity @e[type=ds:simple_domain,r=20,tag=shadow_style] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^8^^ unless entity @e[type=ds:simple_domain,r=20,tag=shadow_style] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s if entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^-8^^ unless entity @e[type=ds:simple_domain,r=20,tag=shadow_style] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] run function dashright

execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^^^-6 if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^8^^ if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^-8^^ if entity @e[type=ds:simple_domain,r=20,tag=shadow_style] run function dashright
execute as @s[scores={DashCD=-201},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^^^-6 unless entity @e[type=ds:simple_domain,r=20,tag=shadow_style] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] run function dashback
execute as @s[scores={DashCD=-202},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^8^^ unless entity @e[type=ds:simple_domain,r=20,tag=shadow_style] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] run function dashleft
execute as @s[scores={DashCD=-203},tag=!wrongwayfinisher,tag=!wrongwayfinisher2,tag=!dying,family=!heavenlyrestriction,tag=domainimmune,tag=!hollowwickerbasket,tag=!domainamplification,tag=!domainactive] at @s unless entity @e[family=damage,family=projectile,family=boss,r=200,scores={EnergyCap=0..,Energy=0..,energystat=0..},tag=DomainExpansion] if entity @e[family=projectile,tag=DomainExpansion,r=55] unless entity @e[family=projectile,tag=DomainExpansion,r=55,name=ChimeraGarden1] if entity @e[type=ds:simple_domain,r=20] positioned ^-8^^ unless entity @e[type=ds:simple_domain,r=20,tag=shadow_style] if entity @e[type=ds:simple_domain,r=10,tag=!shadow_style] run function dashright



scoreboard players set @s[scores={DashCD=!0}] DashCD 0
tag @s[tag=customDashCD] remove customDashCD

