

execute as @s[tag=blackflash_finisher_gojo,tag=limitless] at @s run function blackflash_finisher_gojo

tag @s[scores={blackflashing=3..4},tag=blackflash1,tag=!thezone] add thezone
scoreboard players set @s[scores={blackflashing=3..4},tag=blackflash1] thezone 200
scoreboard players set @s[scores={blackflashing=3..4},tag=blackflash1,hasitem={item=ds:yuji_fists},tag=!sukuna,type=player] thezone 221
execute unless entity @s[tag=has_sukuna,tag=sukuna] run scoreboard players set @s[scores={blackflashing=3..4},tag=blackflash1,family=yuji] thezone 221





execute as @s[scores={blackflashing=9..}] at @s positioned ^^^6 if entity @e[scores={detect_health=0..50},r=5.95,c=1,tag=!blackflash1,tag=!blackflash2,tag=!blackflash3,tag=!blackflash4,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,tag=!nocutscenes,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,family=!grade4,family=!grade3] at @s run function blackflash_finisher_start

execute as @s[scores={blackflashing=9},tag=blackflash1] at @s run effect @a[r=20] night_vision 1 1 true

execute as @s[scores={blackflashing=5}] at @s run scoreboard players random @s expadd 20 100
execute as @s[scores={blackflashing=5},type=!player] at @s unless entity @s[scores={blackflashlearn=0..}] run scoreboard players add @s blackflashlearn 0
execute as @s[scores={blackflashing=5,blackflashlearn=0}] at @s run function blackflash_first

execute as @s[scores={blackflashing=8..9}] at @s anchored eyes run particle ds:heian_impact1 ^^^1.5

execute as @s[scores={blackflashing=8},tag=blackflash1] at @s run title @s[tag=!impactframesoff,type=player] title 
execute as @s[scores={blackflashing=7},tag=blackflash1] at @s run title @s[tag=!impactframesoff,type=player] title 
execute as @s[scores={blackflashing=6},tag=blackflash1] at @s run title @s[tag=!impactframesoff,type=player] title 
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run title @s[tag=!impactframesoff,type=player] title 
execute as @s[scores={blackflashing=4},tag=blackflash1] at @s run title @s[tag=!impactframesoff,type=player] title 
execute as @s[scores={blackflashing=3},tag=blackflash1] at @s run title @s[tag=!impactframesoff,type=player] title 
execute as @s[scores={blackflashing=2},tag=blackflash1] at @s run title @s[tag=!impactframesoff,type=player] title §l
execute as @s[scores={blackflashing=9},tag=blackflash1] at @s run camerashake add @a[r=20] 4 0.25
execute as @s[scores={blackflashing=3},tag=blackflash1] at @s run function damages/blunt_damage
execute as @s[scores={blackflashing=3},tag=blackflash1,tag=yuji_awakened] at @s run function damages/soul_damage


execute as @s[scores={blackflashing=7,blackflash_amount=0..,forms=0..3},type=player,tag=yuji_awakened] at @s positioned ^^^5 if entity @e[r=4.95,family=special_grade,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run scoreboard players add @s blackflash_amount 1
execute as @s[scores={blackflashing=7,blackflash_amount=10..,forms=0..3},type=player,tag=yuji_awakened] at @s positioned ^^^5 if entity @e[r=4.95,family=special_grade,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run tellraw @s {"rawtext":[{"text":"§eYour Experience has grown, you can now advance your §4Cursed Technique§e!"}]}
execute as @s[scores={blackflashing=7,blackflash_amount=0..,forms=0..3},type=player,tag=yuji_awakened] at @s positioned ^^^5 if entity @a[r=4.9,scores={grade=5..},tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,tag=!unselect] unless entity @e[r=4.95,family=special_grade,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run scoreboard players add @s blackflash_amount 1
execute as @s[scores={blackflashing=7,blackflash_amount=10..,forms=0..3},type=player,tag=yuji_awakened] at @s positioned ^^^5 if entity @a[r=4.9,scores={grade=5..},tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,tag=!unselect] unless entity @e[r=4.95,family=special_grade,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run tellraw @s {"rawtext":[{"text":"§eYour Experience has grown, you can now advance your §4Cursed Technique§e!"}]}
scoreboard players add @s[scores={blackflashing=7,blackflash_amount=0..},type=!player] blackflash_amount 1

execute as @s[scores={blackflashing=1..7},tag=blackflash1] at @s positioned ^^^5 run scoreboard players set @e[r=4.95,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 30
execute as @s[scores={blackflashing=7},tag=blackflash1] at @s positioned ^^^5 run scoreboard players operation @e[r=4.95,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] damage += @s damageadd
execute as @s[scores={blackflashing=6..7},tag=blackflash1] at @s positioned ^^^5 run scoreboard players operation @e[r=4.95,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] damage *= seven endurance
execute as @s[scores={blackflashing=7},tag=blackflash1] at @s positioned ^^^5 run scoreboard players add @e[r=4.95,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 20
execute as @s[scores={blackflashing=7},tag=blackflash1] at @s positioned ^^^5 run function damages/blunt_damage
execute as @s[scores={blackflashing=7},tag=blackflash1,tag=yuji_awakened] at @s positioned ^^^5 run function damages/soul_damage
execute as @s[scores={blackflashing=7},tag=blackflash1] at @s positioned ^^^5 run damage @e[r=4.95,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 10 override entity @s
execute as @s[scores={blackflashing=7},tag=blackflash1,tag=yuji_awakened] at @s positioned ^^^5 run scoreboard players add @e[r=4.95,tag=!Frames,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] antiheal 100
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash1 ^^1^1
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash2 ^^1^1
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash3 ^^1^1
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash4 ^^1^1
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash5 ^^1^1
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash6 ^^1^1
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash7 ^^1^1
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash8 ^^1^1
execute as @s[scores={blackflashing=5},tag=blackflash1] at @s run particle ds:black_flash9 ^^1^1
execute as @s[scores={blackflashing=3},tag=blackflash1] at @s run particle ds:dirt2
execute as @s[scores={blackflashing=3},tag=blackflash1] at @s run particle ds:dirt0
execute as @s[scores={blackflashing=3},tag=blackflash1] at @s unless block ~~-0.3~ air run particle ds:crater ~~0.15~
execute as @s[scores={blackflashing=3},tag=blackflash1] at @s unless block ~~-0.3~ air run particle ds:rubble
execute as @s[scores={blackflashing=3},tag=blackflash1] at @s unless block ~~-0.3~ air run particle ds:ground_slam1
execute as @s[scores={blackflashing=3},tag=blackflash1] at @s unless block ~~-0.3~ air run particle ds:leap
execute as @s[scores={blackflashing=9},tag=blackflash1] at @s run playsound mob.blackflash @a ~~~ 100000 1 100000


execute as @s[scores={blackflashing=7},tag=blackflash1] at @s positioned ^^^5 run scoreboard players set @e[r=4.95,tag=!blackflash_finisher_gojo,tag=!blackflash_finisher_gojo2,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Flourish 11


execute unless entity @s[scores={blackflashing=1..}] unless entity @s[tag=blackflash_finisher_gojo,scores={move=421,Frames=430}] run function blackflash_remove