execute as @e[tag=!Frames,scores={strength=35..,punch=1..},type=!player,r=3,c=1] unless entity @s[scores={Hit=1..}] unless entity @s[scores={Stun=21..}] unless entity @s[scores={cutscene=1..}] unless entity @s[scores={move=1..}] unless entity @s[scores={knockdown=1..}] unless entity @s[scores={Flourish=1..}] unless entity @s[scores={domainstart=1..}] unless entity @s[scores={domain=1..}] unless entity @s[scores={Stun=1..},tag=punch0] run tag @s add parry
execute as @e[scores={strength=35..,punch=1..},type=!player,tag=parry,r=3,c=1] run playanimation @s animation.finger_bearer.hit1
execute as @e[scores={strength=35..,punch=1..},type=!player,tag=parry,r=3,c=1] at @s run particle ds:parry1 ^^1.3^1 
execute as @e[scores={strength=35..,punch=1..},type=!player,tag=parry,r=3,c=1] at @s run particle ds:parry2 ^^1.3^1 
execute as @e[scores={strength=35..,punch=1..},type=!player,tag=parry,r=3,c=1] at @s run particle ds:parry3 ^^1.3^1 
execute as @e[scores={strength=35..,punch=1..},type=!player,tag=parry,r=3,c=1] at @s run playsound mob.parry @a[r=100] ~~1~ 99999 4 99999
execute if entity @e[scores={strength=35..,punch=1..},type=!player,tag=parry,r=3,c=1] run kill @s[type=ds:dismantle_quick]



execute as @s run scoreboard players set @e[tag=!Frames,tag=!parry,r=2,c=1,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 1
execute as @s run scoreboard players set @e[tag=!Frames,tag=!parry,r=2,c=1,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 5
execute as @s run scoreboard players add @e[tag=!Frames,tag=!parry,r=2,c=1,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 5
execute as @s run execute as @e[tag=!Frames,tag=!parry,r=2,c=1,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] at @s run playsound mob.blood @a[r=100] ~~~ 9999 4 9999
execute as @s run particle ds:gun4 ~~1~
execute as @s run damage @e[tag=!Frames,tag=!parry,r=2,c=1,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 5 projectile

tag @e[scores={strength=35..,punch=1..},type=!player,tag=parry,r=3,c=1] remove parry
kill @s[type=ds:dismantle_quick]