

#Scoreboard Setup
scoreboard objectives add health_max dummy
scoreboard objectives add health_percent dummy
execute as @a unless entity @s[scores={health_percent=0..}] run scoreboard players set @s health_percent 0
execute as @a unless entity @s[scores={health_max=0..}] run scoreboard players set @s health_max 0
scoreboard players set hundred endurance 100

#Calculation
execute as @a at @s run scoreboard players operation @s health_percent = @s detect_health
execute as @a at @s run scoreboard players operation @s health_percent *= hundred endurance
execute as @a at @s run scoreboard players operation @s health_percent /= @s health_max

scoreboard players set @a[scores={endurance=0,health_max=!40}] health_max 40
scoreboard players set @a[scores={endurance=1,health_max=!44}] health_max 44
scoreboard players set @a[scores={endurance=2,health_max=!48}] health_max 48
scoreboard players set @a[scores={endurance=3,health_max=!52}] health_max 52
scoreboard players set @a[scores={endurance=4,health_max=!56}] health_max 56
scoreboard players set @a[scores={endurance=5,health_max=!60}] health_max 60
scoreboard players set @a[scores={endurance=6,health_max=!64}] health_max 64
scoreboard players set @a[scores={endurance=7,health_max=!68}] health_max 68
scoreboard players set @a[scores={endurance=8,health_max=!72}] health_max 72
scoreboard players set @a[scores={endurance=9,health_max=!76}] health_max 76
scoreboard players set @a[scores={endurance=10,health_max=!80}] health_max 80
scoreboard players set @a[scores={endurance=11,health_max=!84}] health_max 84
scoreboard players set @a[scores={endurance=12,health_max=!88}] health_max 88
scoreboard players set @a[scores={endurance=13,health_max=!92}] health_max 92
scoreboard players set @a[scores={endurance=14,health_max=!96}] health_max 96
scoreboard players set @a[scores={endurance=15,health_max=!100}] health_max 100
scoreboard players set @a[scores={endurance=16,health_max=!104}] health_max 104
scoreboard players set @a[scores={endurance=17,health_max=!108}] health_max 108
scoreboard players set @a[scores={endurance=18,health_max=!112}] health_max 112
scoreboard players set @a[scores={endurance=19,health_max=!116}] health_max 116
scoreboard players set @a[scores={endurance=20,health_max=!120}] health_max 120
scoreboard players set @a[scores={endurance=21,health_max=!124}] health_max 124
scoreboard players set @a[scores={endurance=22,health_max=!128}] health_max 128
scoreboard players set @a[scores={endurance=23,health_max=!132}] health_max 132
scoreboard players set @a[scores={endurance=24,health_max=!136}] health_max 136
scoreboard players set @a[scores={endurance=25,health_max=!140}] health_max 140
scoreboard players set @a[scores={endurance=26,health_max=!144}] health_max 144
scoreboard players set @a[scores={endurance=27,health_max=!148}] health_max 148
scoreboard players set @a[scores={endurance=28,health_max=!152}] health_max 152
scoreboard players set @a[scores={endurance=29,health_max=!156}] health_max 156
scoreboard players set @a[scores={endurance=30,health_max=!160}] health_max 160
scoreboard players set @a[scores={endurance=31,health_max=!164}] health_max 164
scoreboard players set @a[scores={endurance=32,health_max=!168}] health_max 168
scoreboard players set @a[scores={endurance=33,health_max=!172}] health_max 172
scoreboard players set @a[scores={endurance=34,health_max=!176}] health_max 176
scoreboard players set @a[scores={endurance=35,health_max=!180}] health_max 180
scoreboard players set @a[scores={endurance=36,health_max=!184}] health_max 184
scoreboard players set @a[scores={endurance=37,health_max=!188}] health_max 188
scoreboard players set @a[scores={endurance=38,health_max=!192}] health_max 192
scoreboard players set @a[scores={endurance=39,health_max=!196}] health_max 196
scoreboard players set @a[scores={endurance=40,health_max=!200}] health_max 200
scoreboard players set @a[scores={endurance=41,health_max=!204}] health_max 204
scoreboard players set @a[scores={endurance=42,health_max=!208}] health_max 208
scoreboard players set @a[scores={endurance=43,health_max=!212}] health_max 212
scoreboard players set @a[scores={endurance=44,health_max=!216}] health_max 216
scoreboard players set @a[scores={endurance=45,health_max=!220}] health_max 220
scoreboard players set @a[scores={endurance=46,health_max=!224}] health_max 224
scoreboard players set @a[scores={endurance=47,health_max=!228}] health_max 228
scoreboard players set @a[scores={endurance=48,health_max=!232}] health_max 232
scoreboard players set @a[scores={endurance=49,health_max=!236}] health_max 236
scoreboard players set @a[scores={endurance=50,health_max=!240}] health_max 240
scoreboard players set @a[scores={endurance=51,health_max=!244}] health_max 244
scoreboard players set @a[scores={endurance=52,health_max=!248}] health_max 248
scoreboard players set @a[scores={endurance=53,health_max=!252}] health_max 252
scoreboard players set @a[scores={endurance=54,health_max=!256}] health_max 256
scoreboard players set @a[scores={endurance=55,health_max=!260}] health_max 260
scoreboard players set @a[scores={endurance=56,health_max=!264}] health_max 264
scoreboard players set @a[scores={endurance=57,health_max=!268}] health_max 268
scoreboard players set @a[scores={endurance=58,health_max=!272}] health_max 272
scoreboard players set @a[scores={endurance=59,health_max=!276}] health_max 276
scoreboard players set @a[scores={endurance=60,health_max=!280}] health_max 280
scoreboard players set @a[scores={endurance=61,health_max=!284}] health_max 284
scoreboard players set @a[scores={endurance=62,health_max=!288}] health_max 288
scoreboard players set @a[scores={endurance=63,health_max=!292}] health_max 292
scoreboard players set @a[scores={endurance=64,health_max=!296}] health_max 296
scoreboard players set @a[scores={endurance=65,health_max=!300}] health_max 300
scoreboard players set @a[scores={endurance=66,health_max=!304}] health_max 304
scoreboard players set @a[scores={endurance=67,health_max=!308}] health_max 308
scoreboard players set @a[scores={endurance=68,health_max=!312}] health_max 312
scoreboard players set @a[scores={endurance=69,health_max=!316}] health_max 316
scoreboard players set @a[scores={endurance=70,health_max=!320}] health_max 320
scoreboard players set @a[scores={endurance=71,health_max=!324}] health_max 324
scoreboard players set @a[scores={endurance=72,health_max=!328}] health_max 328
scoreboard players set @a[scores={endurance=73,health_max=!332}] health_max 332
scoreboard players set @a[scores={endurance=74,health_max=!336}] health_max 336
scoreboard players set @a[scores={endurance=75,health_max=!340}] health_max 340
scoreboard players set @a[scores={endurance=76,health_max=!344}] health_max 344
scoreboard players set @a[scores={endurance=77,health_max=!348}] health_max 348
scoreboard players set @a[scores={endurance=78,health_max=!352}] health_max 352
scoreboard players set @a[scores={endurance=79,health_max=!356}] health_max 356
scoreboard players set @a[scores={endurance=80,health_max=!360}] health_max 360
scoreboard players set @a[scores={endurance=81,health_max=!364}] health_max 364
scoreboard players set @a[scores={endurance=82,health_max=!368}] health_max 368
scoreboard players set @a[scores={endurance=83,health_max=!372}] health_max 372
scoreboard players set @a[scores={endurance=84,health_max=!376}] health_max 376
scoreboard players set @a[scores={endurance=85,health_max=!380}] health_max 380
scoreboard players set @a[scores={endurance=86,health_max=!384}] health_max 384
scoreboard players set @a[scores={endurance=87,health_max=!388}] health_max 388
scoreboard players set @a[scores={endurance=88,health_max=!392}] health_max 392
scoreboard players set @a[scores={endurance=89,health_max=!396}] health_max 396
scoreboard players set @a[scores={endurance=90,health_max=!400}] health_max 400
scoreboard players set @a[scores={endurance=91,health_max=!404}] health_max 404
scoreboard players set @a[scores={endurance=92,health_max=!408}] health_max 408
scoreboard players set @a[scores={endurance=93,health_max=!412}] health_max 412
scoreboard players set @a[scores={endurance=94,health_max=!416}] health_max 416
scoreboard players set @a[scores={endurance=95,health_max=!420}] health_max 420
scoreboard players set @a[scores={endurance=96,health_max=!424}] health_max 424
scoreboard players set @a[scores={endurance=97,health_max=!428}] health_max 428
scoreboard players set @a[scores={endurance=98,health_max=!432}] health_max 432
scoreboard players set @a[scores={endurance=99,health_max=!436}] health_max 436
scoreboard players set @a[scores={endurance=100,health_max=!440}] health_max 440
scoreboard players set @a[scores={endurance=101,health_max=!444}] health_max 444
scoreboard players set @a[scores={endurance=102,health_max=!448}] health_max 448
scoreboard players set @a[scores={endurance=103,health_max=!452}] health_max 452
scoreboard players set @a[scores={endurance=104,health_max=!456}] health_max 456
scoreboard players set @a[scores={endurance=105,health_max=!460}] health_max 460
scoreboard players set @a[scores={endurance=106,health_max=!464}] health_max 464
scoreboard players set @a[scores={endurance=107,health_max=!468}] health_max 468
scoreboard players set @a[scores={endurance=108,health_max=!472}] health_max 472
scoreboard players set @a[scores={endurance=109,health_max=!476}] health_max 476
scoreboard players set @a[scores={endurance=110,health_max=!480}] health_max 480
scoreboard players set @a[scores={endurance=111,health_max=!484}] health_max 484
scoreboard players set @a[scores={endurance=112,health_max=!488}] health_max 488
scoreboard players set @a[scores={endurance=113,health_max=!492}] health_max 492
scoreboard players set @a[scores={endurance=114,health_max=!496}] health_max 496
scoreboard players set @a[scores={endurance=115,health_max=!500}] health_max 500
scoreboard players set @a[scores={endurance=116,health_max=!504}] health_max 504
scoreboard players set @a[scores={endurance=117,health_max=!508}] health_max 508
scoreboard players set @a[scores={endurance=118,health_max=!512}] health_max 512
scoreboard players set @a[scores={endurance=119,health_max=!516}] health_max 516
scoreboard players set @a[scores={endurance=120,health_max=!520}] health_max 520

scoreboard players set @a[scores={endurance=666,health_max=!760},tag=!120percent] health_max 760
scoreboard players set @a[scores={endurance=666,health_max=!800},tag=120percent] health_max 800


titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=91..},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=81..90},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=71..80},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=61..70},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=51..60},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=41..50},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=31..40},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=21..30},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=11..20},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=0..10},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}

titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=91..},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=81..90},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=71..80},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=61..70},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=51..60},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=41..50},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=31..40},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=21..30},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=11..20},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=0..10},tag=!stats,tag=!menu,tag=!lovetrain,tag=!absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§f❘❘\n\n"}]}


titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=91..},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=81..90},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=71..80},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=61..70},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=51..60},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=41..50},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=31..40},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=21..30},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=11..20},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=0..10},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}

titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=91..},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=81..90},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=71..80},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=61..70},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=51..60},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=41..50},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=31..40},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=21..30},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=11..20},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=0..10},tag=!stats,tag=!menu,tag=lovetrain] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §a§l♣ Fever: "},{"score":{"name":"*","objective":"fever"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}



titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=91..},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=81..90},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=71..80},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=61..70},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=51..60},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=41..50},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=31..40},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=21..30},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=11..20},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=-9999..99,health_percent=0..10},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l "},{"score":{"name":"*","objective":"Evade"}},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}

titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=91..},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=81..90},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=71..80},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=61..70},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=51..60},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=41..50},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=31..40},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=21..30},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=11..20},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}
titleraw @a[tag=!heian_awakening,tag=!plusultra,tag=!plusultra_victim,tag=!plusultra_brother,tag=!delusional_cutscene,scores={Evade=100..,health_percent=0..10},tag=!stats,tag=!menu,tag=absorption] actionbar {"rawtext":[{"text":"\n\n\n             §l§f  §l❘❘ §bCursed Energy §f| "},{"score":{"name":"*","objective":"Energy"}},{"text":"/"},{"score":{"name":"*","objective":"EnergyCap"}},{"text":" | §l❘❘\n§f §l❘❘ §r§f §l❘❘ §4Health §f| §4"},{"score":{"name":"*","objective":"detect_health"}},{"text":"/"},{"score":{"name":"*","objective":"health_max"}},{"text":" §l§f|  \n     §r§f❘❘ §l§8Evasive §f|§l §l§eReady §f|"},{"text":" §l§f|  §r§f❘❘ §l§9XP:§l "},{"score":{"name":"*","objective":"Exp"}},{"text":"§9/"},{"score":{"name":"*","objective":"ExpMax"}},{"text":" §r§f❘❘ §l§gYour Level:§e "},{"score":{"name":"*","objective":"level"}},{"text":" §r§l§l❘❘\n    §r§l❘ §e§l✴ Stored Energy: "},{"score":{"name":"*","objective":"absorption"}},{"text":"%"},{"text":" §r§f❘❘\n\n"}]}











