scoreboard players set @a[tag=!shikigami,scores={ability1=1..}] ability1 0
scoreboard players set @a[tag=!shikigami,scores={ability2=1..}] ability2 0
scoreboard players set @a[tag=!shikigami,scores={ability3=1..}] ability3 0
scoreboard players set @a[tag=!shikigami,scores={ability4=1..}] ability4 0
scoreboard players set @a[tag=!shikigami,scores={ability5=1..}] ability5 0
scoreboard players set @a[tag=!shikigami,scores={ability6=1..}] ability6 0
scoreboard players set @a[tag=!shikigami,scores={ability7=1..}] ability7 0
scoreboard players set @a[tag=!shikigami,scores={ability8=1..}] ability8 0
scoreboard players set @a[tag=!shikigami,scores={ability9=1..}] ability9 0
scoreboard players set @a[tag=!shikigami,scores={ability10=1..}] ability10 0
scoreboard players set @a[tag=!shikigami,scores={ability11=1..}] ability11 0
scoreboard players set @a[tag=!shikigami,scores={ability12=1..}] ability12 0
scoreboard players set @a[scores={wep1=1..}] wep1 0
scoreboard players set @a[scores={wep2=1..}] wep2 0
scoreboard players set @a[scores={wep3=1..}] wep3 0
scoreboard players set @a[scores={wep4=1..}] wep4 0
scoreboard players set @a[scores={wep5=1..}] wep5 0
scoreboard players set @a[scores={wep1v2=1..}] wep1v2 0
scoreboard players set @a[scores={wep2v2=1..}] wep2v2 0
scoreboard players set @a[scores={wep3v2=1..}] wep3v2 0
scoreboard players set @a[scores={wep4v2=1..}] wep4v2 0
scoreboard players set @a[scores={wep5v2=1..}] wep5v2 0
scoreboard players set @a[scores={wep6v2=1..}] wep6v2 0
scoreboard players set @a[scores={domainCD=51..,domain=0,domainstart=0,move=0},tag=!domainactive] domainCD 50

scoreboard players set @a[tag=sukuna,scores={sukuna_ab1=1..}] sukuna_ab1 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab2=1..}] sukuna_ab2 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab3=1..}] sukuna_ab3 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab4=1..}] sukuna_ab4 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab5=1..}] sukuna_ab5 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab6=1..}] sukuna_ab6 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab7=1..}] sukuna_ab7 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab8=1..}] sukuna_ab8 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab9=1..}] sukuna_ab9 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab10=1..}] sukuna_ab10 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab11=1..}] sukuna_ab11 0
scoreboard players set @a[tag=sukuna,scores={sukuna_ab12=51..,domain=0,domainstart=0,move=0},tag=!domainactive] sukuna_ab12 50
scoreboard players set @a[tag=sukuna,scores={sukuna_wep1=1..}] sukuna_wep1 0
scoreboard players set @a[tag=sukuna,scores={sukuna_wep2=1..}] sukuna_wep2 0
scoreboard players set @a[tag=sukuna,scores={sukuna_wep3=1..}] sukuna_wep3 0
scoreboard players set @a[tag=sukuna,scores={sukuna_wep4=1..}] sukuna_wep4 0
scoreboard players set @a[tag=sukuna,scores={sukuna_wep5=1..}] sukuna_wep5 0
scoreboard players set @a[tag=sukuna,scores={sukuna_wep6=1..}] sukuna_wep6 0
