scoreboard players set @a[scores={rct=1800..}] rct 1799
scoreboard players remove @a[scores={rct=1..}] rct 1
scoreboard players remove @a[scores={rct=3..,onfire=1..},tag=!curse] rct 2

damage @a[scores={rct=1..,dying=0},tag=curse] 2 override

execute as @a[scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!curse] at @s run particle ds:rct_aura
execute as @a[scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!curse] at @s run particle ds:rct_aura2
execute as @a[scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!curse] at @s run playsound beacon.ambient @s ~~~ 0.04 2.32
execute as @a[scores={rct=1..,dying=0},tag=curse] at @s run particle ds:rct_aura
execute as @a[scores={rct=1..,dying=0},tag=curse] at @s run particle ds:rct_aura2
execute as @a[scores={rct=1..,dying=0},tag=curse] at @s run playsound beacon.ambient @s ~~~ 0.04 2.32

execute as @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse] at @s as @e[rm=0.15,r=4,c=3,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] unless entity @s[family=!purecurse,tag=!curse] unless entity @s[scores={dying=1..}] run scoreboard players add @s rct 3
execute as @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse] at @s as @e[rm=0.15,r=4,c=3,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] if entity @s[type=player,family=!purecurse,tag=!curse] unless entity @s[scores={dying=1..}] unless entity @s[scores={antiheal=1..}] if entity @s[type=player,scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!rctburnout,tag=!curse] run scoreboard players add @s rct 3
execute as @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse] at @s as @e[rm=0.15,r=4,c=3,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] if entity @s[family=!purecurse,tag=!curse] unless entity @s[scores={dying=1..}] unless entity @s[scores={antiheal=1..}] unless entity @s[type=player,scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!rctburnout,tag=!curse] run effect @s regeneration 1 2 true
execute as @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse] at @s as @e[rm=0.15,r=4,c=3,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] if entity @s[tag=cursed_speech,family=!purecurse,tag=!curse] unless entity @s[scores={dying=1..}] unless entity @s[scores={antiheal=1..}] unless entity @s[type=player,scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!rctburnout,tag=!curse] run scoreboard players add @s speech_repair 1
execute as @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse] at @s as @e[rm=0.15,r=4,c=3,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] if entity @s[family=!small,family=!purecurse,tag=!curse] unless entity @s[scores={dying=1..}] unless entity @s[scores={antiheal=1..}] unless entity @s[type=player,scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!rctburnout,tag=!curse] at @s run particle ds:rct_aura
execute as @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse] at @s as @e[rm=0.15,r=4,c=3,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] if entity @s[family=!small,family=!purecurse,tag=!curse] unless entity @s[scores={dying=1..}] unless entity @s[scores={antiheal=1..}] unless entity @s[type=player,scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!rctburnout,tag=!curse] at @s run particle ds:rct_aura2
execute as @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse] at @s as @e[rm=0.15,r=4,c=3,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] if entity @s[type=player,family=!purecurse,tag=!curse] unless entity @s[scores={dying=1..}] unless entity @s[scores={antiheal=1..}] unless entity @s[type=player,scores={rct=1..,health_percent=0..90,antiheal=0,dying=0},tag=!rctburnout,tag=!curse] at @s run playsound beacon.ambient @s ~~~ 0.04 2.32
execute as @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse] at @s as @e[rm=0.15,r=4,c=3,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] unless entity @s[scores={dying=1..}] run scoreboard players remove @a[hasitem={item=ds:cursedenergy,location=slot.weapon.mainhand},scores={rct=1..,scroll=1,Sneaking=1..,Stun=0,Disabled2=0},tag=rctmaster,tag=!curse,r=0.15,c=1] Energy 3

scoreboard players add @a[tag=cursed_speech,scores={rct=1..,antiheal=0,dying=0},tag=!curse] speech_repair 1
effect @a[scores={rct=1..,health_percent=0..90,Stun=0,antiheal=0,dying=0},tag=!curse] regeneration 1 5 true
effect @a[scores={rct=1..,health_percent=0..90,Stun=1..,antiheal=0,dying=0},tag=!curse] regeneration 1 2 true

scoreboard players remove @a[scores={rct=1..,health_percent=0..90,antiheal=0,dying=0,rctheal=1..},tag=!curse] rctheal 1
effect @a[scores={rct=1..,health_percent=0..90,antiheal=0,dying=0,rctheal=0},tag=!curse] instant_health 1 2 true
scoreboard players set @a[scores={rct=1..,health_percent=0..90,antiheal=0,dying=0,rctheal=0},tag=!curse] rctheal 10

scoreboard players remove @a[scores={rct=1..,health_percent=0..90,dying=0},tag=!heavenlyrestriction,tag=!curse,tag=!rctmaster] Energy 1
scoreboard players remove @a[scores={rct=1..,health_percent=0..90,dying=0},tag=!heavenlyrestriction,tag=!curse] Energy 1
scoreboard players remove @a[scores={rct=1..,dying=0},tag=curse] Energy 2
damage @a[scores={rct=1..,health_percent=0..90,dying=0,Energy=..30},tag=!heavenlyrestriction,tag=!curse] 3 override
damage @a[scores={rct=1..,dying=0,Energy=0..30},tag=curse] 3 override
scoreboard players set @a[scores={rct=1..,dying=0,Energy=..0,reversedcursedCD=!1200..},tag=!heavenlyrestriction,tag=!curse] reversedcursedCD 1200
scoreboard players set @a[scores={rct=4..,Energy=..0},tag=!heavenlyrestriction,tag=!curse] rct 3

damage @a[tag=rctburnout,scores={rct=2..,dying=0,rctuses=0},tag=!curse] 20 override
scoreboard players set @a[tag=rctburnout,scores={rct=2..,dying=0,rctuses=0},tag=!curse] Stun 25
scoreboard players set @a[tag=rctburnout,scores={rct=2..,dying=0,rctuses=0},tag=!curse] Hit 3
scoreboard players set @a[tag=rctburnout,scores={rct=2..,dying=0,rctuses=0},tag=!curse] rct 1



scoreboard players add @a[scores={rct=1..,dying=0},tag=!heavenlyrestriction,tag=!curse] reversecursedCD 1
execute as @a[tag=itemUse:ds:cursedenergy,scores={scroll=1,move=0,ab=0,rct=2..,dying=0},tag=!heavenlyrestriction,tag=!curse] at @s run playsound beacon.deactivate @a ~~~ 1 2
execute as @a[tag=itemUse:ds:cursedenergy,scores={scroll=1,move=0,ab=0,rct=2..,dying=0},tag=!heavenlyrestriction,tag=!curse] at @s run particle ds:rct2 ~~1~
execute as @a[tag=itemUse:ds:cursedenergy,scores={scroll=1,move=0,ab=0,rct=2..,dying=0},tag=!heavenlyrestriction,tag=!curse] at @s run particle ds:rct3 ~~1~
scoreboard players set @a[tag=itemUse:ds:cursedenergy,scores={scroll=1,move=0,ab=0,rct=2..,dying=0},tag=!heavenlyrestriction,tag=!curse] Stun 15
scoreboard players set @a[tag=itemUse:ds:cursedenergy,scores={scroll=1,move=0,ab=0,rct=2..,dying=0},tag=!heavenlyrestriction,tag=!curse] rct 0
