tp @s ~~~
tag @s[tag=!Frames] add Frames
execute at @s if block ~~-0.1~ air run tp @s ~~-0.1~
execute at @s if block ~~-0.1~ air run tp @s ~~-0.1~
execute at @s if block ~~-0.1~ air run tp @s ~~-0.1~

kill @e[type=ds:knockback,r=20]
kill @e[type=ds:red_reverse,r=20]



execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run tag @s[tag=shadow_style] remove shadow_style
execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run particle ds:simple_domain_edge ~~~
execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run particle ds:simple_domain1 ~~~
execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run particle ds:simple_domain2 ~~~
execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run particle ds:simple_domain3 ~~~
execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run particle ds:simple_domain4 ~~~
execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run particle ds:simple_domain5 ~~~
execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run scoreboard players set @e[r=10,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] domainimmune 20
execute unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] run scoreboard players add @e[r=20,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] simpledomainCD 1
playsound beacon.ambient @a[r=20] ~~~ 0.05 1


execute as @s[scores={Deleter=4..},tag=!simpledomain_mobs] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] unless entity @e[r=10,scores={domainimmune=2..,simpledomainown=1..},type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run scoreboard players set @s Deleter 3

execute as @s[scores={Deleter=4..},tag=simpledomain_mobs] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] unless entity @e[type=ds:todo,r=20] unless entity @e[r=10,scores={domainimmune=2..,simpledomainown=1..},tag=!domainactive,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!player] run scoreboard players set @s Deleter 3



execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run tag @s[tag=!shadow_style] add shadow_style
execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain_edge2 ~~~
execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain1b ~~~
execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain2b ~~~
execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain3b ~~~
execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain4b ~~~
execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain5b ~~~
execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run scoreboard players set @e[r=20,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] domainimmune 20
execute if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run scoreboard players add @e[r=20,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] simpledomainCD 1

execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run tag @s[tag=!shadow_style] add shadow_style
execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain_edge2 ~~~
execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain1b ~~~
execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain2b ~~~
execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain3b ~~~
execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain4b ~~~
execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run particle ds:simple_domain5b ~~~
execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run scoreboard players set @e[r=20,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] domainimmune 20
execute if entity @e[type=ds:kusakabe,r=20] unless entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] run scoreboard players add @e[r=20,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] simpledomainCD 1



execute as @s[scores={Deleter=7..},tag=!simpledomain_mobs] if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] unless entity @e[r=20,scores={domainimmune=2..,simpledomainown=1..},type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run scoreboard players set @s Deleter 6
execute as @s[scores={Deleter=7..},tag=simpledomain_mobs] if entity @e[hasitem={item=ds:shadow_style_katana},r=20,tag=!spectator] unless entity @e[type=ds:kusakabe,r=20] unless entity @e[r=20,scores={domainimmune=2..,simpledomainown=1..},tag=!domainactive,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!spectator,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,type=!player] run scoreboard players set @s Deleter 6


execute as @s[scores={Deleter=0..5}] at @s run scoreboard players set @e[r=20,tag=!domainactive] simpledomainCD 300
execute as @s[scores={Deleter=0..5}] at @s run scoreboard players set @e[r=20,tag=!domainactive] Disabled 60