
execute as @e[tag=StatsNPC] at @s run scoreboard players set @a[r=1.5,scores={statopen=0..2}] statopen 3
execute as @e[tag=StatsNPC] at @s unless entity @a[r=1.5,scores={statopen=1..}] run kill @s
titleraw @a[tag=stats,scores={grade=1}] actionbar {"rawtext":[{"text":"❙❙ §r§d§lYour Grade: §cGrade 4 §r❙❙\n"},{"text":"❙❙ §r§l§eInvestment Points:§g "},{"score":{"name":"*","objective":"invest"}},{"text":" §r❙❙ \n\n\n§r❙❙ §aEndurance "},{"score":{"name":"*","objective":"endurance"}},{"text":" ♥ §r❙❙ §4Strength "},{"score":{"name":"*","objective":"strength"}},{"text":" ¤ §r❙❙ §3Agility "},{"score":{"name":"*","objective":"agility"}},{"text":" ☄ §r❙❙ §bCursed Energy Limit "},{"score":{"name":"*","objective":"energystat"}},{"text":" ✦ §r❙❙"}]}
titleraw @a[tag=stats,scores={grade=2}] actionbar {"rawtext":[{"text":"❙❙ §r§d§lYour Grade: §6Grade 3 §r❙❙\n"},{"text":"❙❙ §r§l§eInvestment Points:§g "},{"score":{"name":"*","objective":"invest"}},{"text":" §r❙❙ \n\n\n§r❙❙ §aEndurance "},{"score":{"name":"*","objective":"endurance"}},{"text":" ♥ §r❙❙ §4Strength "},{"score":{"name":"*","objective":"strength"}},{"text":" ¤ §r❙❙ §3Agility "},{"score":{"name":"*","objective":"agility"}},{"text":" ☄ §r❙❙ §bCursed Energy Limit "},{"score":{"name":"*","objective":"energystat"}},{"text":" ✦ §r❙❙"}]}
titleraw @a[tag=stats,scores={grade=3}] actionbar {"rawtext":[{"text":"❙❙ §r§d§lYour Grade: §bGrade 2 §r❙❙\n"},{"text":"❙❙ §r§l§eInvestment Points:§g "},{"score":{"name":"*","objective":"invest"}},{"text":" §r❙❙ \n\n\n§r❙❙ §aEndurance "},{"score":{"name":"*","objective":"endurance"}},{"text":" ♥ §r❙❙ §4Strength "},{"score":{"name":"*","objective":"strength"}},{"text":" ¤ §r❙❙ §3Agility "},{"score":{"name":"*","objective":"agility"}},{"text":" ☄ §r❙❙ §bCursed Energy Limit "},{"score":{"name":"*","objective":"energystat"}},{"text":" ✦ §r❙❙"}]}
titleraw @a[tag=stats,scores={grade=4}] actionbar {"rawtext":[{"text":"❙❙ §r§d§lYour Grade: §aGrade 1 §r❙❙\n"},{"text":"❙❙ §r§l§eInvestment Points:§g "},{"score":{"name":"*","objective":"invest"}},{"text":" §r❙❙ \n\n\n§r❙❙ §aEndurance "},{"score":{"name":"*","objective":"endurance"}},{"text":" ♥ §r❙❙ §4Strength "},{"score":{"name":"*","objective":"strength"}},{"text":" ¤ §r❙❙ §3Agility "},{"score":{"name":"*","objective":"agility"}},{"text":" ☄ §r❙❙ §bCursed Energy Limit "},{"score":{"name":"*","objective":"energystat"}},{"text":" ✦ §r❙❙"}]}
titleraw @a[tag=stats,scores={grade=5..}] actionbar {"rawtext":[{"text":"❙❙ §r§d§lYour Grade: §5Special Grade §r❙❙\n"},{"text":"❙❙ §r§l§eInvestment Points:§g "},{"score":{"name":"*","objective":"invest"}},{"text":" §r❙❙ \n\n\n§r❙❙ §aEndurance "},{"score":{"name":"*","objective":"endurance"}},{"text":" ♥ §r❙❙ §4Strength "},{"score":{"name":"*","objective":"strength"}},{"text":" ¤ §r❙❙ §3Agility "},{"score":{"name":"*","objective":"agility"}},{"text":" ☄ §r❙❙ §bCursed Energy Limit "},{"score":{"name":"*","objective":"energystat"}},{"text":" ✦ §r❙❙"}]}
scoreboard players remove @a[scores={statopen=3..}] statopen 1
execute as @a[scores={statopen=6}] at @s run tp @e[tag=StatsNPC,r=3,c=1] ~~~
execute as @a[scores={statopen=4}] at @s run dialogue open @e[type=npc:npc_custom,c=1] @s