


execute as @p[tag=griefable] unless block ~~1~ bedrock unless block ~~2~ bedrock unless block ~~~ bedrock unless block ~~-1~ bedrock unless block ~~-2~ bedrock run fill ~3~2~3~-3~-2~-3 air
execute as @p[tag=griefable] unless block ~~~ bedrock unless block ~~~ barrier unless block ~~1~ bedrock unless block ~~2~ bedrock unless block ~~3~ bedrock unless block ~~4~ bedrock unless block ~~5~ bedrock unless block ~~6~ bedrock unless block ~~6.5~ bedrock unless block ~~1~ barrier unless block ~~2~ barrier unless block ~~3~ barrier unless block ~~4~ barrier unless block ~~5~ barrier unless block ~~6~ barrier unless block ~~6.5~ barrier unless block ~~-1~ bedrock unless block ~~-2~ bedrock unless block ~~-3~ bedrock unless block ~~-4~ bedrock unless block ~~-5~ bedrock unless block ~~-6~ bedrock unless block ~~-6.5~ bedrock unless block ~~-1~ barrier unless block ~~-2~ barrier unless block ~~-3~ barrier unless block ~~-4~ barrier unless block ~~-5~ barrier unless block ~~-6~ barrier unless block ~~-6.5~ barrier run structure load mystructure:13x13diamond ~-6.5~-6.5~-6.5

tag @e[r=6.99,tag=!form9s,scores={infinity=1..},tag=Frames,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] remove Frames
scoreboard players set @e[r=6.99,tag=!form9s,scores={infinity=4..},type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] infinity 3
scoreboard players set @e[r=6.99,tag=!form9s,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,family=!heavenlyrestriction] Stun 45
execute as @e[r=6.99,tag=!form9s,family=heavenlyrestriction] unless entity @s[scores={Hit=0,flashstep=0,Stun=0..20,Move=0,move=0,cutscene=0,knockdown=0,Flourish=0,DashCD=0,Frames=3..9}] run scoreboard players set @s Stun 45
scoreboard players set @e[r=6.99,tag=!form9s,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,family=!heavenlyrestriction] Hit 10
execute as @e[r=6.99,tag=!form9s,family=heavenlyrestriction] unless entity @s[scores={Hit=0,flashstep=0,Stun=0..20,Move=0,move=0,cutscene=0,knockdown=0,Flourish=0,DashCD=0,Frames=3..9}] run scoreboard players set @s Hit 10
scoreboard players add @e[r=6.99,tag=!form9s,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,family=!heavenlyrestriction] Evade 10
execute as @e[r=6.99,tag=!form9s,family=heavenlyrestriction] unless entity @s[scores={Hit=0,flashstep=0,Stun=0..20,Move=0,move=0,cutscene=0,knockdown=0,Flourish=0,DashCD=0,Frames=3..9}] run scoreboard players set @s Evade 10
execute as @e[r=6.99,tag=!form9s,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] unless entity @s[scores={detect_health=0..300}] unless entity @s[scores={Hit=0,flashstep=0,Stun=0..20,Move=0,move=0,cutscene=0,knockdown=0,Flourish=0,DashCD=0,Frames=3..9},family=heavenlyrestriction] run particle ds:blood_mist ~~1~
execute as @e[r=6.99,tag=!form9s,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] unless entity @s[scores={detect_health=0..300}] unless entity @s[scores={Hit=0,flashstep=0,Stun=0..20,Move=0,move=0,cutscene=0,knockdown=0,Flourish=0,DashCD=0,Frames=3..9},family=heavenlyrestriction] run playsound mob.blood2 @a[r=200] ~~-5~ 9999 2 9999

execute as @e[r=6.99,tag=!form9s,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] unless entity @s[scores={detect_health=0..150}] unless entity @s[scores={Hit=0,flashstep=0,Stun=0..20,Move=0,move=0,cutscene=0,knockdown=0,Flourish=0,DashCD=0,Frames=3..9},family=heavenlyrestriction] run damage @s 150 suicide

execute as @e[r=6.99,tag=!form9s,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand,tag=!wcs_death_cutscene] if entity @s[scores={detect_health=0..150}] unless entity @s[scores={Hit=0,flashstep=0,Stun=0..20,Move=0,move=0,cutscene=0,knockdown=0,Flourish=0,DashCD=0,Frames=3..9},family=heavenlyrestriction] run tag @s add wcs_death_cutscene
execute as @e[r=6.99,tag=!form9s,type=!item,family=!projectile,family=!despawncito,family=!damage,family=!disappear,type=!xp_orb,type=!arrow,type=!thrown_trident,type=!fireball,type=!dragon_fireball,type=!small_fireball,type=!fireworks_rocket,type=!fishing_hook,type=!splash_potion,type=!area_effect_cloud,type=!snowball,type=!egg,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] if entity @s[scores={detect_health=0..150}] unless entity @s[scores={Hit=0,flashstep=0,Stun=0..20,Move=0,move=0,cutscene=0,knockdown=0,Flourish=0,DashCD=0,Frames=3..9},family=heavenlyrestriction] run scoreboard players set @s sukunacutscene 141

execute if entity @e[tag=sukuna,tag=form9s,c=1,r=80,scores={move=1..}] positioned ^^^7 run function wcs_damage3