execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run damage @e[tag=!Frames,type=!ds:ember_insect,r=14.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 2 override
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,r=14.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] onfire 3
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run scoreboard players set @e[tag=!Frames,type=!ds:ember_insect,r=14.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 18
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run scoreboard players set @e[tag=!Frames,type=!ds:ember_insect,r=14.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 4
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,r=14.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 2
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run camerashake add @a[r=100] 0.2 0.08
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run playsound mob.burn @a[r=100] ~~~ 0.17 2
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run playsound mob.blaze.shoot @a[r=100] ~~~ 0.17 2
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run playsound mob.blaze.shoot @a[r=100] ~~~ 0.17 0.5
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run  effect @a[r=100] night_vision 1 1 true
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] if entity @e[tag=griefable] run function flames/heat15x15
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] run function damages/fire_damage
execute as @e[c=1,scores={move=25..84},r=125,tag=Frames,tag=flames] positioned ^^^15 run function flames/eternalblaze
