execute if entity @s[r=14.99] run playsound mob.blaze.shoot @a[r=50] ~~~ 0.2 0.5
execute if entity @s[r=14.99] run playsound mob.burn @a[r=50] ~~~ 0.2 2
execute if entity @s[r=14.99] run damage @e[tag=!Frames,tag=!flames,family=!jogo,type=!ds:geyser,type=!ds:ember_insect,r=2.49,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 1 override
execute if entity @s[r=14.99] run scoreboard players set @e[tag=!Frames,tag=!flames,family=!jogo,type=!ds:geyser,type=!ds:ember_insect,r=2.49,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 10
execute if entity @s[r=14.99] run scoreboard players set @e[tag=!Frames,tag=!flames,family=!jogo,type=!ds:geyser,type=!ds:ember_insect,r=2.49,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 2
execute if entity @s[r=14.99] run scoreboard players add @e[tag=!Frames,tag=!flames,family=!jogo,type=!ds:geyser,type=!ds:ember_insect,r=2.49,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] onfire 2
execute if entity @s[r=14.99] run scoreboard players add @e[tag=!Frames,tag=!flames,family=!jogo,type=!ds:geyser,type=!ds:ember_insect,r=2.49,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 2
execute if entity @s[r=14.99] run scoreboard players set @e[tag=!Frames,tag=!flames,family=!jogo,type=!ds:geyser,type=!ds:ember_insect,r=2.49,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 10
execute if entity @s[r=14.99] if entity @e[tag=griefable] run function flames/heat2x2
execute if entity @s[r=14.99] run function damages/fire_damage
execute positioned ~~2.5~ if entity @s[r=14.99] run function flmes/geyser_floor_damage