execute as @s[scores={Deleter=18..19}] at @s run playsound random.explode @a[r=50] ~~~ 9999 0.6 99999
execute as @s[scores={Deleter=18..19}] at @s run camerashake add @a[r=50] 4 0.25
execute as @s[scores={Deleter=1..}] at @s run playsound bubble.up @a[r=50] ~~~ 99999 0.55 99999
execute as @s[scores={Deleter=1..19}] at @s run playsound mob.blaze.shoot @a[r=50] ~~~ 99999 0.5 99999
execute as @s[scores={Deleter=1..19}] at @s run playsound mob.burn @a[r=50] ~~~  99999 0.5 99999
execute as @s[scores={Deleter=1..19}] at @s run playsound mob.blaze.shoot @a[r=50] ~~~ 99999 0.5 99999
execute as @s[scores={Deleter=1..19}] at @s run camerashake add @a[r=50] 0.05 0.05

execute as @s[scores={Deleter=19..}] at @s run particle ds:firewall1


execute as @s[scores={Deleter=18..19}] at @s run particle ds:volcanic_launch1
execute as @s[scores={Deleter=18..19}] at @s run particle ds:volcanic_launch2
execute as @s[scores={Deleter=18..19}] at @s run particle ds:volcanic_launch3
execute as @s[scores={Deleter=18..19}] at @s run particle ds:volcanic_launch4
execute as @s[scores={Deleter=18..19}] at @s run particle ds:volcanic_launch5
execute as @s[scores={Deleter=18..19}] at @s run particle ds:volcanic_launch6
execute as @s[scores={Deleter=18..19}] at @s run particle ds:firewall1
execute as @s[scores={Deleter=18..19}] at @s run particle ds:firewall2
execute as @s[scores={Deleter=1..16}] at @s unless score griefing Mode = three Mode if entity @e[tag=griefable] unless entity @e[family=damage,tag=DomainExpansion,r=50,type=!ds:malevolent_kitchen,type=!ds:incomplete_shrine] unless entity @s[tag=lavaoff] run fill ~3~~3 ~-3 ~1 ~-3 lava [] replace air
execute as @s[scores={Deleter=1..16}] at @s unless score griefing Mode = three Mode if entity @e[tag=griefable] unless entity @e[family=damage,tag=DomainExpansion,r=50,type=!ds:malevolent_kitchen,type=!ds:incomplete_shrine] unless entity @s[tag=lavaoff] run fill ~5~~5 ~-5 ~ ~-5 lava [] replace air


execute as @s[scores={Deleter=1..19}] at @s run scoreboard players set @s atk 2
execute as @s[scores={Deleter=1..19}] at @s run damage @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 1 override
execute as @s[scores={Deleter=1..19}] at @s run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] onfire 1
execute as @s[scores={Deleter=1..19}] at @s run effect @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] levitation 1 21 true
execute as @s[scores={Deleter=1..19}] at @s run scoreboard players set @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 4
execute as @s[scores={Deleter=1..19}] at @s run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 1

execute as @s[scores={Deleter=1..19}] at @s  positioned ~~5~ run damage @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 1 override
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~5~ run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] onfire 1
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~5~ run effect @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] levitation 1 21 true
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~5~ run scoreboard players set @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 4
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~5~ run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 1

execute as @s[scores={Deleter=1..19}] at @s  positioned ~~10~ run damage @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 1 override
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~10~ run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] onfire 1
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~10~ run effect @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] levitation 1 21 true
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~10~ run scoreboard players set @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 4
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~10~ run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 1


execute as @s[scores={Deleter=1..19}] at @s  positioned ~~15~ run damage @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 1 override
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~15~ run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] onfire 1
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~15~ run effect @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] levitation 1 21 true
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~15~ run scoreboard players set @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 4
execute as @s[scores={Deleter=1..19}] at @s  positioned ~~15~ run scoreboard players add @e[tag=!Frames,type=!ds:ember_insect,tag=!flames,r=4.99,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 1
execute as @s[scores={Deleter=1..19}] at @s  if entity @e[tag=griefable] run function flames/heat3x9
execute as @s[scores={Deleter=1..19}] at @s run function damages/fire_damage
