playanimation @s[scores={move=39},tag=form7c,tag=shikigami] animation.piercing_water

scoreboard players set @s[scores={move=3..},tag=form7c,tag=shikigami] Move 5

tag @s[scores={move=1..2},tag=form7c,tag=shikigami] remove form7c

tag @s[scores={move=34..,Stun=1..},tag=form7c,tag=shikigami] remove form7c
scoreboard players set @s[scores={move=34..,Stun=1..},tag=form7c,tag=shikigami] move 0
execute as @s[scores={move=9..30},tag=form7b,tag=shikigami] at @s positioned ^0.2 ^1 ^0.33 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7b,tag=shikigami] at @s positioned ^0.2 ^1 ^0.66 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7b,tag=shikigami] at @s positioned ^0.2 ^1 ^0.99 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7b,tag=shikigami] at @s positioned ^0.2 ^1 ^1.32 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^1.65 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^1.98 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^2.31 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^2.64 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^2.97 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^3.30 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^3.63 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^3.96 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^4.29 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^4.62 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^4.95 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^5.28 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^5.61 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^5.94 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^6.27 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^6.60 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^6.93 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^7.26 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^7.59 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^7.92 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^8.25 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^8.58 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^8.91 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^9.24 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^9.57 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^9.90 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^10.23 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^10.56 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^10.89 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^11.22 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^11.55 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^11.88 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^12.21 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^12.54 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^12.87 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^13.20 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^13.53 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^13.86 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^14.19 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^14.52 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^14.85 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^15.18 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^15.51 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^15.84 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^16.17 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^16.50 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^16.83 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^17.16 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^17.49 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^17.82 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^18.15 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^18.48 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^18.81 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^19.14 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^19.47 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^19.80 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^20.13 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^20.46 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^20.79 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^21.12 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^21.45 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^21.78 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^22.11 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^22.44 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^22.77 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^23.10 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^23.43 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^23.76 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^24.09 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^24.42 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^24.75 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^25.08 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^25.41 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^25.74 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^26.07 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^26.40 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^26.73 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^27.06 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^27.39 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^27.72 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^28.05 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^28.38 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^28.71 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^29.04 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^29.37 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^29.70 run function shikigami/shikigami/piercing_water
execute as @s[scores={move=9..30},tag=form7c,tag=shikigami] at @s positioned ^0.2 ^1.22 ^30.03 run function shikigami/shikigami/piercing_water
