tag @s[tag=itemUse:ds:gavel2,tag=!wepclick] add wepclick
execute as @s[tag=itemUse:ds:gavel2] at @s run function judgeman/gavel_clicks

scoreboard players set @s[scores={BasicM1=1..,Stun=0}] M1Reset 15
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..4}] Disabled 2
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..5}] AfterAnim 14
scoreboard players set @s[scores={BasicM1s=5..}] Disabled 25
scoreboard players set @s[scores={BasicM1=1..2,BasicM1s=5..,Stun=0}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=6..}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=1..,Stun=1..}] BasicM1s 0



tag @s[hasitem={item=ds:gavel2,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] add switch
execute as @s[hasitem={item=ds:gavel2,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=1..,Energy=10..,detect_left=1..},tag=doublesneak] at @s run playsound note.pling @a ~~~ 0.05 0.4
execute as @s[hasitem={item=ds:gavel2,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=1..,Energy=10..,detect_left=1..},tag=doublesneak] at @s run tellraw @s {"rawtext":[{"text":"§cGavel Switch is on cooldown: §e"},{"score":{"name": "@p","objective": "wep5"}},{"text":"§c."}]}
scoreboard players set @s[hasitem={item=ds:gavel2,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] move 11
scoreboard players set @s[hasitem={item=ds:gavel2,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] wep5 13
scoreboard players remove @s[hasitem={item=ds:gavel2,location=slot.weapon.mainhand},scores={Energy=10..,move=11,detect_left=1..},tag=doublesneak] Energy 10

scoreboard players set @s[scores={BasicM1=1}] BasicM1 0

effect @s[hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] weakness 1 99 true

playanimation @s[scores={BasicM1=0,detect_sneak=0,BasicM1s=0,Stun=0,ab=0,move=0,AfterAnim=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] animation.gavel2.idle

scoreboard players random @s[scores={BasicM1=3,BasicM1s=1..,Stun=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand},tag=!heavenlyrestriction] blackflashchance 1 269
scoreboard players set @s[scores={BasicM1=3,BasicM1s=1..,Stun=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand},tag=blackflashrig,tag=!heavenlyrestriction] blackflashchance 7

scoreboard players add @s[scores={detect_left=1,BasicM1=0,BasicM1s=0..5,Disabled=0,detect_sneak=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] BasicM1s 1

execute as @s[scores={BasicM1=5..},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] run function stance_animate_gavel2
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=1,Stun=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] BasicM1 7
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=2,Stun=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] BasicM1 8
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=3,Stun=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] BasicM1 10
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=4,Stun=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] BasicM1 10
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=5,Stun=0},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] BasicM1 12

scoreboard players set @s[scores={BasicM1s=5..}] Move 15
scoreboard players set @s[scores={BasicM1s=5..,BasicM1=1..5}] Camera 15

scoreboard players set @s[scores={BasicM1=3..5,BasicM1s=1..3},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] atk 2

execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 run scoreboard players operation @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.witch.throw @a[r=80] ~~~ 1 0.75
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 if entity @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2.15 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 if entity @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 2.14 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 run scoreboard players add @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 run damage @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 2 override
execute as @s[scores={BasicM1=3,BasicM1s=1..2},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 run scoreboard players add @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 12
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 run scoreboard players add @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 3
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 run scoreboard players add @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 6
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^2.3 run scoreboard players add @e[tag=!Frames,r=2.25,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6


execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players operation @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 if entity @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2.15 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 if entity @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 2.14 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run damage @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 2 override
execute as @s[scores={BasicM1=3,BasicM1s=1..2},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 12
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 2
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 6
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 4

scoreboard players set @s[scores={BasicM1=4..,BasicM1s=5..}] Frames 5

execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players operation @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s if entity @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2 10000
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s if entity @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.864 10000
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run damage @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 2 override
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6

execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players operation @e[tag=!Frames,r=4.5,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s if entity @e[tag=!Frames,r=4.5,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2 10000
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s if entity @e[tag=!Frames,r=4.5,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.864 10000
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run damage @e[tag=!Frames,r=4.5,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 2 override
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=6,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6

scoreboard players set @s[scores={BasicM1=3..5,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] atk 2
execute as @s[scores={BasicM1=1..7,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run tp @s ~~~
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players operation @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=3..7,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run execute as @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=3..7,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand},c=1,r=4.5]
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s if entity @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s if entity @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.864 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run damage @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 4 override
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=4.5,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Flourish 8

execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players operation @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=3..7,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run execute as @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=3..7,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand},c=1,r=6]
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s if entity @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s if entity @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.864 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run damage @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 4 override
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run scoreboard players add @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Flourish 5

execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run tp @s @s
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run camerashake add @a[r=8] 1 0.15
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ~~~ run particle ds:dirt0
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ~~~ run particle ds:ground_slam2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ~~~ run particle ds:ground_slam1
execute as @s[scores={BasicM1=7,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ~~~ run playsound mob.witch.throw @a[r=40] ~~~ 9999 0.75 9999
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s positioned ~~~ run playsound mob.witch.throw @a[r=40] ~~~ 9999 0.4 9999
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run camerashake add @a[r=8] 2 0.15

execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run function damages/blunt_damage
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] at @s run function damages/blunt_damage


scoreboard players set @s[scores={BasicM1=1..3,BasicM1s=1..4},hasitem={item=ds:gavel2,location=slot.weapon.mainhand}] BasicM1 0