tag @s[tag=itemUse:ds:gavel3,tag=!wepclick] add wepclick
execute as @s[tag=itemUse:ds:gavel3] at @s run function judgeman/gavel_clicks

scoreboard players set @s[scores={BasicM1=1..,Stun=0}] M1Reset 30
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..3}] Disabled 4
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..5}] AfterAnim 23
scoreboard players set @s[scores={BasicM1s=4..}] Disabled 60
scoreboard players set @s[scores={BasicM1=1..2,BasicM1s=4..,Stun=0}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=6..}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=1..,Stun=1..}] BasicM1s 0

tag @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep4=0,Energy=200..,detect_left=1..,detect_jump=1..,detect_sprint=1..},tag=!doublesneak] add wep4
execute as @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep4=1..,Energy=200..,detect_left=1..,detect_jump=1..,detect_sprint=1..},tag=!doublesneak] at @s run tellraw @s {"rawtext":[{"text":"§cBig Bonk is on cooldown: §e"},{"score":{"name": "@p","objective": "wep4"}},{"text":"§c."}]}
scoreboard players set @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep4=0,Energy=200..,detect_left=1..,detect_jump=1..,detect_sprint=1..},tag=!doublesneak] move 81
scoreboard players set @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep4=0,Energy=200..,detect_left=1..,detect_jump=1..,detect_sprint=1..},tag=!doublesneak] wep4 1200
scoreboard players remove @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Energy=200..,detect_left=1..,detect_jump=1..,detect_sprint=1..,move=81},tag=!doublesneak] Energy 200

tag @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] add switch
execute as @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=1..,Energy=10..,detect_left=1..},tag=doublesneak] at @s run playsound note.pling @a ~~~ 0.05 0.4
execute as @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=1..,Energy=10..,detect_left=1..},tag=doublesneak] at @s run tellraw @s {"rawtext":[{"text":"§cGavel Switch is on cooldown: §e"},{"score":{"name": "@p","objective": "wep5"}},{"text":"§c."}]}
scoreboard players set @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] move 11
scoreboard players set @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] wep5 13
scoreboard players remove @s[tag=wepclick,hasitem={item=ds:gavel3,location=slot.weapon.mainhand},scores={Energy=10..,move=11,detect_left=1..},tag=doublesneak] Energy 10

scoreboard players set @s[scores={BasicM1=1}] BasicM1 0

effect @s[hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] weakness 1 99 true

playanimation @s[scores={BasicM1=0,detect_sneak=0,BasicM1s=0,Stun=0,ab=0,move=0,AfterAnim=0},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] animation.gavel3.idle

scoreboard players random @s[scores={BasicM1=3,BasicM1s=1..,Stun=0},hasitem={item=ds:gavel3,location=slot.weapon.mainhand},tag=!heavenlyrestriction] blackflashchance 1 269
scoreboard players set @s[scores={BasicM1=3,BasicM1s=1..,Stun=0},hasitem={item=ds:gavel3,location=slot.weapon.mainhand},tag=blackflashrig,tag=!heavenlyrestriction] blackflashchance 7

scoreboard players add @s[scores={detect_left=1,BasicM1=0,BasicM1s=0..5,Disabled=0,detect_sneak=0},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] BasicM1s 1

execute as @s[scores={BasicM1=5..},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] run function stance_animate_gavel3
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=1,Stun=0},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] BasicM1 17
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=2,Stun=0},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] BasicM1 17
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=3,Stun=0},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] BasicM1 13
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=4,Stun=0},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] BasicM1 20

scoreboard players set @s[scores={BasicM1s=4..}] Move 20
scoreboard players set @s[scores={BasicM1s=4..,BasicM1=1..5}] Camera 20

scoreboard players set @s[scores={BasicM1=3..5,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] atk 2

execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2.15 run scoreboard players operation @e[tag=!Frames,r=2.1,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=4,BasicM1s=1..},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run camerashake add @a[r=10] 0.5 0.15 
execute as @s[scores={BasicM1=7,BasicM1s=1},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.heavy_swing @a[r=80] ~~~ 0.5 1.33
execute as @s[scores={BasicM1=7,BasicM1s=2},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.heavy_swing @a[r=80] ~~~ 0.5 1.25
execute as @s[scores={BasicM1=7,BasicM1s=3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.heavy_swing @a[r=80] ~~~ 0.5 1.45
execute as @s[scores={BasicM1=11,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.heavy_swing @a[r=80] ~~~ 0.5 1
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2.15 if entity @e[tag=!Frames,r=2.1,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch1 @a[r=80] ~~~ 10000 1.75 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2.15 if entity @e[tag=!Frames,r=2.1,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.14 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2.15 run scoreboard players add @e[tag=!Frames,r=2.1,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 3
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2.15 run damage @e[tag=!Frames,r=2.1,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 5 override
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2.15 run scoreboard players add @e[tag=!Frames,r=2.1,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 16
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2.15 run scoreboard players add @e[tag=!Frames,r=2.1,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 4


execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players operation @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 if entity @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch1 @a[r=80] ~~~ 10000 1.75 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 if entity @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.14 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 3
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run damage @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 5 override
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 16
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 4


scoreboard players set @s[scores={BasicM1=3..5,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] atk 2
execute as @s[scores={BasicM1=1..7,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s run tp @s @s
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players operation @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3..7,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run execute as @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=3..7,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand},c=1]
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 if entity @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch1 @a[r=80] ~~~ 10000 1.6 10000
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 if entity @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.264 10000
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 5
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run damage @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 10 override
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 9
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=3.95,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] knockdown 30

execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players operation @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3..7,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run execute as @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=3..7,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand},c=1]
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 if entity @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch1 @a[r=80] ~~~ 10000 1.6 10000
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 if entity @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.264 10000
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 5
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run damage @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 10 override
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 9
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=6,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] knockdown 30

execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s run function damages/blunt_damage
execute as @s[scores={BasicM1=3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s run function damages/blunt_damage

execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:crater2
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:dirt0
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:rising_strike2
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:rising_strike2
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:leap
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:dirt2
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:rubble3
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:ground_slam1
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:ground_slam1
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:ground_slam2
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:ground_slam3
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run particle ds:judge_slam1
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run camerashake add @a[r=25] 3 0.25
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run playsound beacon.power @a[r=25] ~~~ 99999 1.25 99999
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run playsound random.explode @a[r=25] ~~~ 99999 0.5 99999
execute as @s[scores={BasicM1=3,BasicM1s=4},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] at @s positioned ^^^2 run playsound mob.wither.break_block @a[r=25] ~~~ 99999 0.5 99999

scoreboard players set @s[scores={BasicM1=1..3,BasicM1s=1..3},hasitem={item=ds:gavel3,location=slot.weapon.mainhand}] BasicM1 0