tag @s[tag=itemUse:ds:gavel1,tag=!wepclick] add wepclick
execute as @s[tag=itemUse:ds:gavel1] at @s run function judgeman/gavel_clicks

scoreboard players set @s[scores={BasicM1=1..,Stun=0}] M1Reset 15
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..4}] Disabled 2
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..5}] AfterAnim 16
scoreboard players set @s[scores={BasicM1s=5..}] Disabled 55
scoreboard players set @s[scores={BasicM1=1..2,BasicM1s=5..,Stun=0}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=6..}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=1..,Stun=1..}] BasicM1s 0



tag @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep3=0,Sneaking=1..,punch=1,Energy=80..},tag=!doublesneak] add wep3
execute as @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep3=1..,Sneaking=1..,punch=1,Energy=1..79},tag=!doublesneak] at @s run playsound note.pling @a ~~~ 0.05 0.4
execute as @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep3=1..,Sneaking=1..,punch=1,Energy=80..},tag=!doublesneak] at @s run tellraw @s {"rawtext":[{"text":"§cHead Smash is on cooldown: §e"},{"score":{"name": "@p","objective": "wep3"}},{"text":"§c."}]}
scoreboard players set @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep3=0,Sneaking=1..,punch=1,Energy=80..},tag=!doublesneak] move 41
scoreboard players set @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep3=0,Sneaking=1..,punch=1,Energy=80..},tag=!doublesneak] wep3 400
scoreboard players remove @s[tag=wepclick,hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,punch=1,Energy=80..,move=41},tag=!doublesneak] Energy 80

tag @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] add switch
execute as @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=1..,Energy=10..,detect_left=1..},tag=doublesneak] at @s run playsound note.pling @a ~~~ 0.05 0.4
execute as @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=1..,Energy=10..,detect_left=1..},tag=doublesneak] at @s run tellraw @s {"rawtext":[{"text":"§cGavel Switch is on cooldown: §e"},{"score":{"name": "@p","objective": "wep5"}},{"text":"§c."}]}
scoreboard players set @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] move 11
scoreboard players set @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep5=0,Energy=10..,detect_left=1..},tag=doublesneak] wep5 13
scoreboard players remove @s[tag=wepclick,hasitem={item=ds:gavel1,location=slot.weapon.mainhand},scores={Energy=10..,move=11,detect_left=1..},tag=doublesneak] Energy 10

scoreboard players set @s[scores={BasicM1=1}] BasicM1 0

effect @s[hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] weakness 1 99 true

playanimation @s[scores={BasicM1=0,detect_sneak=0,BasicM1s=0,Stun=0,ab=0,move=0,AfterAnim=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] animation.gavel1.idle

scoreboard players random @s[scores={BasicM1=3,BasicM1s=1..,Stun=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand},tag=!heavenlyrestriction] blackflashchance 1 269
scoreboard players set @s[scores={BasicM1=3,BasicM1s=1..,Stun=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand},tag=blackflashrig,tag=!heavenlyrestriction] blackflashchance 7

scoreboard players add @s[scores={detect_left=1,BasicM1=0,BasicM1s=0..5,Disabled=0,detect_sneak=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] BasicM1s 1

execute as @s[scores={BasicM1=5..},hasitem={item=ds:gavel1,location=slot.weapon.mainhand},c=1] run function stance_animate_gavel1
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=1,Stun=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] BasicM1 7
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=2,Stun=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] BasicM1 7
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=3,Stun=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] BasicM1 8
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=4,Stun=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] BasicM1 6
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=5,Stun=0},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] BasicM1 12

scoreboard players set @s[scores={BasicM1s=5..}] Move 15
scoreboard players set @s[scores={BasicM1s=5..,BasicM1=1..5}] Camera 15

scoreboard players set @s[scores={BasicM1=3..5,BasicM1s=1..3},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] atk 2

execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players operation @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.witch.throw @a[r=80] ~~~ 1 0.75
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 if entity @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2.15 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 if entity @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 2.14 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run damage @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 2 override
execute as @s[scores={BasicM1=3,BasicM1s=1..2},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 12
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 3
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 6
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6


execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players operation @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 if entity @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2.15 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 if entity @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 2.14 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run damage @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 2 override
execute as @s[scores={BasicM1=3,BasicM1s=1..2},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 12
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 2
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 6
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^3.15 run scoreboard players add @e[tag=!Frames,r=3.1,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 4


execute as @s[scores={BasicM1=11,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s run playsound mob.witch.throw @a ~~~ 1 0.36
execute as @s[scores={BasicM1=11,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s run particle ds:weapon_toss ^0.5^1^1

scoreboard players set @s[scores={BasicM1=3..5,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] atk 2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.witch.throw @a[r=80] ~~~ 1 0.5
execute as @s[scores={BasicM1=1..7,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s run tp @s ~~~
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 run scoreboard players operation @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=3..7,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 run execute as @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=3..7,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand},c=1]
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 if entity @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 if entity @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.864 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 run scoreboard players add @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 run damage @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 4 override
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 run scoreboard players add @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 run scoreboard players add @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 6
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^2.35 run scoreboard players add @e[tag=!Frames,r=2.3,tag=!Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] knockdown 35

execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s run camerashake add @a[r=8] 2 0.15


execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players operation @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] damagehalf += @s damageadd
execute as @s[scores={BasicM1=3..7,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 run execute as @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] at @s run tp @s ~~~ facing @e[scores={BasicM1=3..7,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand},c=1]
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 if entity @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound mob.punch @a[r=80] ~~~ 10000 2 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 if entity @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] run playsound random.explode @a[r=80] ~~~ 10000 1.864 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 run damage @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] 4 override
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Stun 22
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] Evade 15
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^4 run scoreboard players add @e[tag=!Frames,r=3.95,tag=Big,type=!item,type=!ds:projectile,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!ds:dash0,type=!ds:dash,type=!ds:dash2,type=!arrow,tag=!unselect,type=!falling_block,type=!ds:knockback,type=!ds:lapse_explode,type=!ds:red_reversal,type=!armor_stand] knockdown 35

execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s run tp @s @s
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.5 run particle ds:crater
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.5 run particle ds:leap
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.5 run playsound random.explode @a[r=80] ~~~ 10000 1.25 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.5 run playsound mob.wither.break_block @a[r=80] ~~~ 99999 1.1 99999
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s positioned ^^^1.5 run playsound random.explode @a[r=80] ~~~ 10000 2 10000

execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s run function damages/blunt_damage
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] at @s run function damages/blunt_damage


scoreboard players set @s[scores={BasicM1=1..3,BasicM1s=1..4},hasitem={item=ds:gavel1,location=slot.weapon.mainhand}] BasicM1 0