
tag @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=0,wep1=0,Sneaking=0,Energy=25..,detect_jump=0},tag=!doublesneak] add wep1
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep1=0,Energy=0..24,Sneaking=0,detect_jump=0},tag=!doublesneak] at @s run playsound note.pling @s ~~~ 0.05 0.87
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=0,wep1=1..,Sneaking=0,Energy=25..,detect_jump=0},tag=!doublesneak] at @s run playsound note.pling @s ~~~ 0.05 0.4
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=0,wep1=1..,Sneaking=0,Energy=25..,detect_jump=0},tag=!doublesneak] at @s run tellraw @s {"rawtext":[{"text":"§cInfinity Backhand is on cooldown: §e"},{"score":{"name": "@p","objective": "wep1"}},{"text":"§c."}]}
scoreboard players set @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep1=0,Sneaking=0,Energy=25..,detect_jump=0},tag=!doublesneak] move 31
scoreboard players set @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep1=0,Sneaking=0,Energy=25..,detect_jump=0},tag=!doublesneak] wep1 300
scoreboard players remove @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Energy=25..,move=31,Sneaking=0,detect_jump=0},tag=!doublesneak] Energy 25

tag @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,wep2=0,Sneaking=1..,Energy=50..},tag=!doublesneak] add wep2
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep2=0,Energy=0..49,Sneaking=1..},tag=!doublesneak] at @s run playsound note.pling @s ~~~ 0.05 0.87
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,wep2=1..,Sneaking=1..,Energy=50..},tag=!doublesneak] at @s run playsound note.pling @s ~~~ 0.05 0.4
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,wep2=1..,Sneaking=1..,Energy=50..},tag=!doublesneak] at @s run tellraw @s {"rawtext":[{"text":"§cFury Barrage is on cooldown: §e"},{"score":{"name": "@p","objective": "wep2"}},{"text":"§c."}]}
scoreboard players set @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep2=0,Sneaking=1..,Energy=50..},tag=!doublesneak] move 121
scoreboard players set @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep2=0,Sneaking=1..,Energy=50..},tag=!doublesneak] wep2 900
scoreboard players remove @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Energy=50..,move=121,Sneaking=1..},tag=!doublesneak] Energy 50

tag @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=0,wep3=0,Sneaking=0,Energy=30..,detect_jump=1},tag=!doublesneak] add wep3
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep3=0,Energy=0..29,Sneaking=0,detect_jump=1},tag=!doublesneak] at @s run playsound note.pling @s ~~~ 0.05 0.87
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=0,wep3=1..,Sneaking=0,Energy=30..,detect_jump=1},tag=!doublesneak] at @s run playsound note.pling @s ~~~ 0.05 0.4
execute as @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=0,wep3=1..,Sneaking=0,Energy=30..,detect_jump=1},tag=!doublesneak] at @s run tellraw @s {"rawtext":[{"text":"§cShockwave Punch is on cooldown: §e"},{"score":{"name": "@p","objective": "wep3"}},{"text":"§c."}]}
scoreboard players set @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep3=0,Sneaking=0,Energy=30..,detect_jump=1},tag=!doublesneak] move 21
scoreboard players set @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,wep3=0,Sneaking=0,Energy=30..,detect_jump=1},tag=!doublesneak] wep3 220
scoreboard players remove @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand},scores={Energy=30..,move=21,Sneaking=0,detect_jump=1},tag=!doublesneak] Energy 30

tag @s[tag=!domainamplification,hasitem={item=ds:limitless_fists,location=slot.weapon.mainhand}] remove limitlessclick