

execute as @s[tag=itemUse:ds:flames_fists] at @s run function flames/use_flames_heavy


tag @s[hasitem={item=ds:flames_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,wep4=0,punch=1,Energy=125..}] add wep4
execute as @s[hasitem={item=ds:flames_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,wep4=1..,punch=1,Energy=125..}] at @s run playsound note.pling @a ~~~ 0.05 0.4
execute as @s[hasitem={item=ds:flames_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,wep4=1..,punch=1,Energy=125..}] at @s run tellraw @s {"rawtext":[{"text":"§cInferno Quake is on cooldown: §e"},{"score":{"name": "@p","objective": "wep4"}},{"text":"§c."}]}
scoreboard players set @s[hasitem={item=ds:flames_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,wep4=0,punch=1,Energy=125..}] move 56
scoreboard players set @s[hasitem={item=ds:flames_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,wep4=0,punch=1}] wep4 900
scoreboard players remove @s[hasitem={item=ds:flames_fists,location=slot.weapon.mainhand},scores={Stun=0,Disabled2=0,Sneaking=1..,punch=1,Energy=125..,move=56}] Energy 125


scoreboard players set @s[scores={BasicM1=1..,Stun=0}] M1Reset 25
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..5}] Disabled 3
scoreboard players set @s[scores={BasicM1=1..,BasicM1s=1..5}] AfterAnim 10
scoreboard players set @s[scores={BasicM1s=5..}] Disabled 34
scoreboard players set @s[scores={BasicM1=1..2,BasicM1s=5..,Stun=0}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=6..}] BasicM1s 0
scoreboard players set @s[scores={BasicM1s=1..,Stun=1..}] BasicM1s 0

scoreboard players set @s[scores={BasicM1=1}] BasicM1 0

effect @s[hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] weakness 1 99 true

scoreboard players random @s[scores={BasicM1=6,BasicM1s=1..,Stun=0},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand},tag=!heavenlyrestriction] blackflashchance 1 269
scoreboard players set @s[scores={BasicM1=6,BasicM1s=1..,Stun=0},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand},tag=blackflashrig,tag=!heavenlyrestriction] blackflashchance 7

scoreboard players add @s[scores={detect_left=1,BasicM1=0,BasicM1s=0..5,Disabled=0,detect_sneak=0},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] BasicM1s 1


execute as @s[scores={BasicM1=5..},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] run function stance_animate_fire
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=1,Stun=0},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] BasicM1 8
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=2,Stun=0},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] BasicM1 8
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=3,Stun=0},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] BasicM1 7
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=4,Stun=0},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] BasicM1 6
scoreboard players add @s[scores={detect_left=1,BasicM1=0,Disabled=0,detect_sneak=0,BasicM1s=5,Stun=0},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] BasicM1 15

execute as @s[scores={BasicM1=6}] at @s run playsound mob.blaze.shoot @a[r=20] ~~~ 9999 0.8 9999
execute as @s[scores={BasicM1=6}] at @s run playsound mob.burn @a[r=20] ~~~ 0.2 1


scoreboard players set @s[scores={BasicM1=4,BasicM1s=1..3},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] atk 2

execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run execute as @e[tag=!Frames,r=1.8,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] at @s run function flames/fire_hit
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^2.85 run execute as @e[tag=!Frames,r=2.8,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] at @s run function flames/fire_hit

execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players operation @e[tag=!Frames,r=1.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.witch.throw @a ~~~ 1 0.75
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 if entity @e[tag=!Frames,r=1.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run playsound mob.punch @a ~~~ 10000 1.95 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run damage @e[tag=!Frames,r=1.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 5 override
execute as @s[scores={BasicM1=3,BasicM1s=1..2},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 16
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 9
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 6
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^1.85 run scoreboard players add @e[tag=!Frames,r=1.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 6


execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3.85 run scoreboard players operation @e[tag=!Frames,r=4.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3.85 if entity @e[tag=!Frames,r=4.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run playsound mob.punch @a ~~~ 10000 1.95 10000
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3.85 run damage @e[tag=!Frames,r=4.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 5 override
execute as @s[scores={BasicM1=3,BasicM1s=1..2},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 16
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 9
execute as @s[scores={BasicM1=3,BasicM1s=3},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Stun 6
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3.85 run scoreboard players add @e[tag=!Frames,r=4.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 6

scoreboard players set @s[scores={BasicM1=3..,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] Move 4
scoreboard players set @s[scores={BasicM1=3..5,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] atk 2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^0.5 run playsound mob.witch.throw @a ~~~ 1 0.5
execute as @s[scores={BasicM1=1..7,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s run tp @s @s
execute as @s[scores={BasicM1=1..2,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s run tp @s ^^^-2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^2.85 run scoreboard players operation @e[tag=!Frames,r=2.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^2.85 run scoreboard players add @e[tag=!Frames,r=2.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^2.85 run damage @e[tag=!Frames,r=2.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 12 override
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^2.85 run scoreboard players add @e[tag=!Frames,r=2.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] knockdown 80
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^2.85 run scoreboard players add @e[tag=!Frames,r=2.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 15
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^2.85 run effect @e[tag=!Frames,r=2.8,tag=!Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] levitation 1 17 true

execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^4.85 run scoreboard players operation @e[tag=!Frames,r=5.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] damage += @s damageadd
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^4.85 if entity @e[tag=!Frames,r=5.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] run playsound mob.punch @a ~~~ 10000 2 10000
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^4.85 run scoreboard players add @e[tag=!Frames,r=5.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Hit 2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^4.85 run damage @e[tag=!Frames,r=5.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] 12 override
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^4.85 run scoreboard players add @e[tag=!Frames,r=5.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] knockdown 80
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^4.85 run scoreboard players add @e[tag=!Frames,r=5.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] Evade 15
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^4.85 run effect @e[tag=!Frames,r=5.849,tag=Big,type=!item,family=!projectile,family=!despawncito,family=!damage,type=!xp_orb,type=!arrow,type=!falling_block,tag=!unselect,type=!ds:lapse_explode,type=!ds:red_reversal,type=!ds:hollow_nuke,type=!ds:limitless_explosion,type=!ds:pressure,type=!ds:energy_explosion,type=!ds:massive_bomb,type=!ds:shrine_dmg,type=!ds:pachinko_impact1,type=!ds:bolt_explode,type=!ds:shikigami_impact,type=!ds:oxrushex,type=!gg:impact_frame,type=!armor_stand] levitation 1 17 true


execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:fire_downslam1 
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:fire_downslam2 
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:fire_downslam3 
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:fire_downslam4 
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:fire_downslam5 
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:fire_downslam6 
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:fire_downslam7 
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:rubble3
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:ground_slam2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run particle ds:dirt0
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 run camerashake add @a[r=100] 2 0.25
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 unless block ~~-0.25~ air run particle ds:fire_crater1
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 unless block ~~-0.25~ air run particle ds:fire_crater2
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 unless block ~~-0.25~ air run playsound random.explode @a[r=100] ~~~ 9999 0.5 9999
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 unless block ~~-0.25~ air run playsound random.explode @a[r=100] ~~~ 9999 0.75 9999
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 unless block ~~-0.25~ air run playsound mob.wither.break_block @a[r=100] ~~~ 9999 0.5 9999
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s positioned ^^^3 unless block ~~-0.25~ air run playsound mob.shock1 @a[r=100] ~~~ 9999 0.5 9999
execute as @s[scores={BasicM1=4,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s run summon ds:red_reverse ^^^-0.15

execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s run function damages/blunt_damage
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s run function damages/blunt_damage
execute as @s[scores={BasicM1=3,BasicM1s=5},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s run function damages/fire_damage
execute as @s[scores={BasicM1=3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] at @s run function damages/fire_damage

scoreboard players set @s[scores={BasicM1=1..3,BasicM1s=1..4},hasitem={item=ds:flames_fists,location=slot.weapon.mainhand}] BasicM1 0